from xml.dom.minidom import Document
from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

document = Document()

# profile picture

document.add_picture('images.png', width=Inches(2.0))

# name, phone number and email

name = input('what is your name? ')
speak('hello' + name)
speak('what is your phone number?')
Phone_number = input('what is your phone number? ')
speak('i would like to know your email address')
email = input('what is your email? ')

document.add_paragraph(
   name + ' | ' + Phone_number + ' | ' + email 
)

# about me

document.add_heading('About me')
speak('Great! now tell me about yourself')
document.add_paragraph(input('tell me about yourself? '))

# work experience

document.add_heading('Work Experience')
p = document.add_paragraph()

speak('we are progressing, lets talk about your work experience, which company have you worked for?')
company = input('Enter Name of Company ')
speak('when did you start?')
start_date = input('Start Date ')
speak('when did you stop?')
end_date = input('End Date ')

p.add_run(company + ' ' + ' ' + '------').bold = True
p.add_run(start_date + ' ' + '-' + ' ' + end_date + ' ' '\n').italic = True

speak('impressive!, so describe your experience at' + company)
experience_details = input('Describe your experiece at ' + company + ' ')

p.add_run(experience_details)

# more experiences

while True:
    speak('do you have more experience?')
    more_experience = input('Do you have more experience? YES or NO ')
    if more_experience.lower() == 'yes':
        p = document.add_paragraph()

        speak('please, state the name of the company')
        company = input('Enter Name of Company ')
        speak('when did you start')
        start_date = input('Start Date ')
        speak('and when did you stop')
        end_date = input('End Date ')

        p.add_run(company + ' ' + ' ' + '------').bold = True
        p.add_run(start_date + ' ' + '-' + ' ' + end_date + ' ' '\n').italic = True

        speak('woww!!!, please describe your experience at' + company)
        experience_details = input('Describe your experiece at ' + company + ' ')

        p.add_run(experience_details)
    else:
        break

# skills

document.add_heading('Skills')
speak('what about your skills?, tell me about your skills')
skill = input('Enter Skill ')
p = document.add_paragraph(skill)
p.style = 'List Bullet'

# more skills

while True:
    speak('okay!!, do you have more skills?')
    more_skills = input('Do You Have More Skills? YES or NO ')
    if more_skills.lower() == 'yes':
        skill = input('Enter Skill ')
        p = document.add_paragraph(skill)
        p.style = 'List Bullet'
    else:
        break

# footter
section = document.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = "CV generated by Emy_python"

document.save('cv.docx')

